version: "3.3"
services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=xalmi
      - MYSQL_USER=
      - MYSQL_ROOT_PASSWORD=runrun
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    volumes:
      - ./database/data/mysql_data:/var/lib/mysql
